# Description:
#   Robot is very David
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot inspire me
#
# Author:
#	Aaron

remarks = [
    "A battle like this isn’t one we can do on our own.",
    "A cog, slave to someone else’s dream in hopes of surviving another day.",
    "A hidden city inside my mind, my cat running away, me trying to find a way out and leading my family to a place of safety.",
    "A life without Him is more painful than any words could ever describe.",
    "A simple step out of our comfort zone and learning to see things from a different perspective will go a long way in helping us stay focused and carry on.",
    "A situation can either be viewed positively or dreadfully.",
    "A trip to my local coffee shop started a journey that would profoundly alter the way I viewed my surroundings.",
    "Above all, never stop believing in who you are.",
    "Above all, share how you feel whether it's by writing it down or calling a trusted friend.",
    "Above all, we need God.",
    "Abraham Lincoln sums this up quite well.",
    "Accepting His love, mercy and grace is what keeps our constantly spinning lives in order and on the right path.",
    "After a very surprising and insightful conversation about transparency in business and the benefits of it, I realized that I’m worth far more than anything of value in this world.",
    "After I heard the sad news I began to wonder, will I be ready if my number is called?",
    "Ajahn Chah, a man respected and loved for his wisdom, has this to say, “If you let go a little, you will have a little peace. If you let go a lot, you will have a lot of peace.”",
    "All too often, we allow this to happen instead of looking beyond our problems that may actually be smaller than they appear.",
    "All work and no play ring loudly in your ears.",
    "Allow your mind to enter a place of peace, where it’s just you and your thoughts.",
    "Although we near the end of our rope, we hang on.",
    "Among the thousands of messages constantly being broadcasted to us at a moment’s notice, finding clarity in our thoughts and emotions allows us to find a sense of meaning.",
    "Any fear can be overshadowed by enthusiasm and morning to night activity.",
    "Arm yourself financially; know that life will be so much easier if you just abide by this simple concept.",
    "As a people, and as a nation we are blessed far more than we realize, and it is from this that there is room for all the other fears to creep in.",
    "As a result, we suffer from a genuine, valuable connection with someone else, knowing that we matter, and feeling as if we belong.",
    "As human beings, we can only digest the world through selective perception.",
    "As humans, we often overlook the power of choice.",
    "As I briefly glanced at the list of items to do, I knew something had to be done, and that progress of recent events must continue.",
    "As I look up into the dark, early morning night sky, the dream that caused me to wake up at 5 am replays freshly in my mind.",
    "As I shared my order with the barista, I noticed her energetic and upbeat spirit.",
    "As I snapped back to the present, the universe tied in another interesting lesson.",
    "As I watch my neighbors begin their days, walking their dogs with heads held low, I know deep down that a difference can be made.",
    "As kids, our schools encouraged creativity through classes like art and music.",
    "As kids, these words were meant to comfort us whenever we lost a game or failed a test, but the true knowledge of never giving up is often later learned when we’re suddenly faced with adult challenges.",
    "As my mind continued to wander, it occurred to me that the bubble we’ve created around ourselves has not only protected us from the things we don’t want but is also blocking out the things we truly need.",
    "As of today, you should make it your duty to get up and explore a hobby.",
    "As the battle inside rages on, he wonders of he has the strength to carry on.",
    "As the moon illuminated my seat on the patio, I asked myself, what would you do if your time to accomplish great things wasn’t later or when things were perfect, but instead right now?",
    "As the stars begin to fade into streaks of the orange and yellow of the early morning sun, I know the battle of another day has begun.",
    "As we live each day, let’s stop to focus on just what we are blessed with.",
    "At any given moment, hundreds if not more type of odds are against you.",
    "At some point, this kindness will come back to you, especially when you least expect it.",
    "At some point, we will die.",
    "At the end of each day, when the neighborhood gets quiet and everyone turns in for their nights rest, my second day begins.",
    "At the end of the day, everything becomes clear, and at the end of the day, there’s hope for a better day.",
    "At the end of the day, he knows God is holding His hand, carrying him through the valleys of the shadows of death and restoring hope within his soul.",
    "At the end of the day, we all are bound to be true to ourselves, to those around us.",
    "At the end of the day, what does it all mean, the pain, the hurt, the sadness and the small glimmer of hope?",
    "At the end of the day, your children deserve the best.",
    "At the start of each week, we gain a brand new opportunity, one that if you truly think about it, is given to us daily.",
    "At this moment, I dream of a day where giving back to the community is more than a website or design service, but something tangible and above all, something that changes lives and communities for the better.",
    "At this moment, you are stronger than you were before.",
    "At this moment, you can look around and see that you’ve survived.",
    "Bad things happen all the time, but you don’t have to sit back and accept it as all that life has to offer.",
    "Be good at many things, great at a few things.",
    "Be the best you, even when you don’t feel like it.",
    "Be the person everyone looks up to, and then be better.",
    "Be your own cheerleader.",
    "Because no matter how many all-nighters you’ve pulled, or how talented you are, after a certain point, there is nothing more that you can do and you have no choice, but to rely on God.",
    "Because of your experience of falling, you can face the next day with strength and confidence.",
    "Before we are able to channel any of our energy into solving someone else’s problem we need to deeply examine ourselves.",
    "Believe that you are.",
    "Believe that you will.",
    "Breaking free from a burdensome life is a choice.",
    "Brutal reality",
    "But at what point do you admit that you need rest?",
    "But he’s come too far to quit, too far to give up now.",
    "But in this confusing and awkward moment of life, there are these weird moments that make everything including the future okay.",
    "But this is why I wrote this book…",
    "By allowing our thoughts to be of a more positive nature, we open ourselves up to better connections with others.",
    "By taking a moment to interact with our loved ones, we allow ourselves the ability to partake of the joy in our surroundings.",
    "Causing a positive effect upon just one life can change your perspective, improve your relationships and can have a massive ripple effect of good upon our surroundings.",
    "Challenge yourself to do better.",
    "Chances are that at some point, one or more of these thoughts have crossed your mind.",
    "Chances are that person isn’t even thinking about you.",
    "Chances are that they are no different than you were at their age.",
    "Constantly we seek paths of ease, fame and fortune, yet we fail to see that our basic human side, the part that loves, and hurts and that gets excited is being lost due to our overwhelming desire of more and easier.",
    "Constantly, the thought races through my mind as my heart sinks in my chest.",
    "Could this all be just a bad dream?",
    "Create a container for your mind.",
    "Cross over to the guy or girl that seems to have it all.",
    "Daily we forget the author of all good things, the universe’s first master designer.",
    "Dealing with your feelings of fear and confusion are the hardest to deal with.",
    "Deep down within these moments I pray, asking for the answer and hoping for a better day.",
    "Despite all the noise, fears of not being good enough to the desire to give up without even trying should instead be embraced instead of rejected, for we can use these emotions to fuel us to be successful and make a big difference.",
    "Despite having an unexpectedly great weekend, starting a new week just didn’t sit well with me.",
    "Despite race, gender, or sexual preference, we are all one and the same, for we all breathe the same air and require the same things in order to survive.",
    "Despite the obstacles we face in life, now is the time we push harder, live better, and love those around us with open hearts and minds.",
    "Do something, anything, as long as you take the first step.",
    "Don’t be afraid to cry.",
    "Don’t be afraid to feel.",
    "Don’t feel as if you’re going through the struggle by yourself.",
    "Don’t give up, for you’ve been given a wonderful gift that is so rare, each day it should inspire you to do better, to create more good.",
    "Don’t let anger take control.",
    "Don’t let fear master you, instead master your fears and use them to live fully.",
    "Don’t let life put you in a corner.",
    "Don’t let yourself fall into a routine of being a monster.",
    "Don’t live a life filled with regrets of chances not taken, or opportunities passed.",
    "Don’t poison the fountain.",
    "Don’t stop looking for the positive.",
    "Dragging myself out of the comfortable confines of my home office, I ventured out and decided to work from my local Starbucks.",
    "Each day he wakes up, hoping that things will get better, only to see them get worse.",
    "Each day we should choose to accept the circumstances we can’t change and find the strength in doing our best to change the things we can.",
    "Each day, the scenes of our lives playout roughly the same, with few variations and lots of frustrations.",
    "Each moment is a new opportunity to take a step in a positive direction.",
    "Each morning, have a notebook handy and take a look in the mirror.",
    "Each new day, hour, and minute we have the chance to do just that.",
    "Each of us will face a different journey from fear to happiness, but the general rules are the same.",
    "Each one of us is capable of being above average and solving many of life’s problems.",
    "Each thought adds more worry than the one before.",
    "Either way, we have to be careful not to manipulate ourselves into thinking this is always the case.",
    "Embrace the moment and be thankful for what you currently have.",
    "Embrace the struggle and be amazing!",
    "Embrace them.",
    "Embracing the struggle isn’t about giving in, it’s about using it as leverage to win.",
    "Embracing the struggle isn’t always easy, which is why having a supportive network around you can help put things into balance.",
    "Emotions are only temporary.",
    "Emotions are temporary and send us on a rollercoaster of ups and downs.",
    "Erma Bombeck gives us one way in which we can approach the obstacle of ourselves when she says, “When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left, and could say, ‘I used everything you gave me.’”",
    "Even if no one tells you in your adulthood, it is important that you repeat this principle to yourself over and over again.",
    "Even in the face of difficulty, with Him, you can conquer anything.",
    "Even though sometimes I find myself at a point in time where taking action on the goals set is actually scary, I know that I can’t do it alone.",
    "Even though the paths we walk daily rarely take us to such heights that rockets do, we still face the challenges of our own forces.",
    "Even when life seems as if it is going in a positive direction, the feeling that something bad may happen just won’t go away.",
    "Eventually, the fear of being alone or failing appears less significant.",
    "Eventually, there is a subconscious effort of doing one thing differently, and you’ll start turning your fears into an adventure of discovery and growth.",
    "Eventually, we will prevail and triumph, but the journey to that point is filled with twists and turns.",
    "Ever since he was suddenly let go, everything has been a blur as if nothing was real anymore.",
    "Ever so often, it seems that my brain is trying to tell me something, trying to show me a message that I can’t understand.",
    "Every day I hope for the best and fear the worst.",
    "Everyday we put on the disguise that things are ok, but deep down inside, there is a raging storm full of draining emotions.",
    "Everything you do now is under severe scrutiny.",
    "Exactly nothing good will happen until we realign our focus from the negative and put it on something positive.",
    "Experience after experience, with new insights, gained from simply connecting with those around us, there is a true personal connection with the good that life has to offer.",
    "Explore is not another book that promises to give you the secrets to happiness.",
    "Extend a hand to someone who needs to know that things will be okay.",
    "Facing the brutal truth is hard work, and doing it alone is a recipe for disaster.",
    "Failure to stand for something good only means we support bad.",
    "Fallen from grace, he turns his head up to the sky, lets out a prayer for strength, courage and wisdom.",
    "Fear is a state of mind, one that we create because it keeps us safe in our comfort zone.",
    "Fear is everywhere and in everything.",
    "Fear isn’t weakness but is actually your biggest strength.",
    "Fear will grip you in ways that can never be imagined, but only within this adversity we can triumph.",
    "Fear ≠ weakness.",
    "Fight for more than just things.",
    "Fight for something good.",
    "Fight for the moments that bring warmth to your soul.",
    "Fight to create more good.",
    "Fighting for God’s love isn’t pointless but instead, is the ultimate point.",
    "Fill your life with a standard of living that goes beyond being mediocre.",
    "Finally, there is a place of peace, where despite all the troubles surrounding him, he believes that he can.",
    "finding peace",
    "Finding peace in the midst of chaos and uncertainty isn’t easy.",
    "Focus on your strengths and what you love, rather than your weaknesses and what you hate.",
    "For your Father in heaven knows the number of hairs on your head.",
    "Forward, onward he must go.",
    "Forward.",
    "Frankly, we are to be blamed for this.",
    "Friends, we must wholly trust in God.",
    "From the very moment you turn the other cheek like Jesus and make it a daily practice, your life will drastically improve for the better.",
    "Gaining all the wealth in the world and being a horrible individual to others will in the end, be the loneliest of times.",
    "Get a hobby.",
    "Get the frustrations out in a healthy way.",
    "Get up and kick it in the face! Go ahead and cry, scream and yell.",
    "Getting back up after being knocked down may not seem like something pleasant, especially when you have bumps and bruises.",
    "Give thanks, and help someone instead of complaining.",
    "Giving in and doing things the same way as everyone else isn’t going to make you happy.",
    "Giving in to hopelessness is not an option.",
    "Giving over our fears to God allows us to believe in the light that shines within us that will never die.",
    "Giving up fear transforms us to be a believer of something more.",
    "Giving up seems easy, yet for some reason I just can’t give in to the thoughts of negativity and despair.",
    "Go for a walk and take a camera with you to capture precious moments.",
    "Got a grudge you’ve been holding on to?",
    "Grab a cup of tea or your favorite drink and let us embark on a journey away from our fears and closer to happiness.",
    "Have a place you’ve always wanted to travel to?",
    "Having clean surroundings and fresh air are extremely important.",
    "Having faith and not doing anything is simply wishful thinking, and that gets us nowhere.",
    "Having the idea is half the work; it’s time to roll up your sleeves and put in the effort to make your dreams a reality.",
    "He cares and wants us to care as well.",
    "He has a purpose for you.",
    "He lays awake in bed, wondering what the next step will be and what his next job will be.",
    "He says, “I am not bound to win, but I am bound to be true.” Life isn’t always about winning, and even though it may often seem like a competition, it really isn’t.",
    "He sneaks up when we least expect it, and is relentless in his pursuit of our demise.",
    "Hesitate no longer.",
    "He’s like a big brother that is always there, a father who always has your back, and a friend who knows just what you’re going through without you having to say a word.",
    "His strength limited, he calls upon the higher strength, God’s strength, to pull him through.",
    "Holding on during the storm.",
    "Honestly, I’ve been told this countless times in my life, but it was never at the times when I needed to hear it the most.",
    "Hope is the answer in such an uncertain space.",
    "How are the relationships around you?",
    "How can this be fixed?",
    "How do we move past the fear that causes us to continually miss out on our hopes and dreams and achieve the peace we so desperately seek to attain?",
    "How do you keep your head held up high?",
    "How does one hold on in such gut wrenching times?",
    "However, I couldn’t have come to this conclusion without realizing this one lesson that without bad, I wouldn’t have appreciated the good.",
    "However, I recently discovered why Mondays are so special.",
    "However, in each and every one of us, a superhero resides, patiently waiting for that special moment to save the day.",
    "However, instead of allowing myself to fall into an unproductive state, I decided to make it a learning adventure.",
    "However, instead of looking inward for fulfillment, we should look outward and aim to help mend the broken and hurting around us.",
    "However, just like our outward environment needing to be clean, our inner environments must also be clean.",
    "However, many of us choose to settle for average instead.",
    "However, on a very basic level, we pine for a sense of belonging.",
    "However, there is hope in turning these feelings around into something good.",
    "However, those who are meek shall inherit the kingdom.",
    "However, unlike many, I have learned to be determined and never give up.",
    "However, we need to rise above such fears and embrace our weaknesses, hand in hand with those around us.",
    "However, you won’t be alone; the journey is one worth traveling together.",
    "Humanity isn’t just filled with robot-like people who don’t care; it’s also filled with hundreds of communities passionate about hope, and communities that are more than just neat rows of houses and good schools, but where people actually care and believe in each other.",
    "Hundreds of people die daily - some friends, some family, some total strangers.",
    "I borrowed this from a quote, but let the message ring clear.",
    "I could brag about all the opportunities that come my way, each with its own unique attraction, yet I feel humbled to the point where bragging seems mundane and unbecoming of a servant of the Creator, and besides what good is bragging anyway?",
    "I don’t know, but one thing I do know is that once I spread my wings and jump, there is no turning back.",
    "I guess tomorrow will be the same thing all over again.",
    "I have goals and visions of a better tomorrow.",
    "I hope you will be blessed and inspired as I have been in writing this book.",
    "I mean seriously and wholeheartedly trust God.",
    "I must keep going, for what I’ve been through will all be for nothing if I give up now.”",
    "I must say, I’ve always been conservative with how I spend my money, but I could have saved more aggressively in preparation for my entrepreneurial path.",
    "I say malarkey.",
    "I should also point out that it will take more than faith to win the battle.",
    "I started feeling frustrated as a result of not being able to figure out why I felt this way.",
    "I will never stop believing in who I am and what I can accomplish, because one day, it’ll all be worth it.",
    "If all your basic needs were met, what would you do with your time?",
    "If during this time, tears begin to fight for a chance to stream down your face, let it happen.",
    "If only he could break the spell, then he’d win the battle for sure.",
    "If only we could see this.",
    "If only we listened and offered a helping hand, we would realize just how good things are for us.",
    "If only we would stop and listen to those around us who are broken, hurting, and holding on to the hope of a better tomorrow.",
    "If the first step isn’t taken, the journey can never begin.",
    "If this is not your desire, find a community that welcomes you and makes you feel like you belong.",
    "If we consistently feel as if nothing good will happen, then guess what?",
    "If we rely on strictly emotions, it’s easy to get sidetracked from the good right in front of us and the positive tomorrow we seek.",
    "If we were to break free of the mental slavery that we face daily, what would be the first thing done?",
    "If you don’t trust your own self to at least try to achieve something more than what you’ve settled for, then sadly, you will still be sitting in the same situation you have been in for a while now.",
    "If you haven’t used a particular item in a while, maybe it’s time for it to go.",
    "If you stumble, don’t crumble.",
    "If you’re like me, these questions are ones in which you struggle with daily.",
    "If, instead of jumping to conclusions, we jumped to help someone in need, we would be a little better off.",
    "Imagine if you will, one day you wake up, holding a bag of lemons, with no memory of how you ended up with them.",
    "In each of us, at our very core is a longing to connect with those around us, a longing to heal the broken hearted and to establish a common baseline of genuine connections.",
    "In fact, our purpose isn’t even a secret at all.",
    "In fact, worrying will not make things better, but worse.",
    "In life, there never will be a time where things are simple and without worry.",
    "In order to fight, some anger towards something must be present.",
    "In our daily lives, we should strive to be more like Elisha, having ridiculous amounts of faith, and if you have no idea who Elisha is, look him up.",
    "In our exploration for some time away from the constant pain and disappointment we face, we will sometimes find it difficult to understand and adapt to situations often out of our control.",
    "In our increasingly competitive marketplace, where mediocrity is no longer good enough, we all are charged with doing more.",
    "In our over connected culture, we’ve lost the very humanity of our individuality.",
    "In technology terms, our altered lines of code that have pushed us onto a path filled with self-centered desire have enabled its homing beacon, showing us the way back home.",
    "In the end, I came away with a simple mantra.",
    "In the end, I received a simple answer: why… NOT?",
    "In the end, will it be worth isolating ourselves and even building enemies in exchange for losing the ones who care?",
    "In this space of time, a call is being given, but will we answer?",
    "In those times when you’re waiting on the perfect moment to step outside of the problems you face, you need to ask yourself, do you want to win or lose?",
    "Instead of allowing ourselves to relax and embrace the serenity waiting to be enjoyed, we battle daily against ourselves and the ultimate variable - the variable of time.",
    "Instead of being so eagerly divided, stepping on the heads of those who have a similar dream of succeeding in life, we should all focus more on giving selflessly and loving unconditionally.",
    "Instead of complaining about not being able to buy the latest cell phone, or latest pair of shoes, let us reflect and realize that in many places there are people like you and me fighting just to find a meal to quiet the hunger pains, that we are fortunate to be in a warm bed each night, food and entertainment within easy reach, and more clothes than some will ever see in their lifetime.",
    "Instead of setting out with a mindset of “what is in it for me,” go out there with a passion and determination to offer a solution to a problem or need, and simply allow your work to do the speaking.",
    "Instead, focus on the lesson to be learned.",
    "Instead, it is a book that will transform the way you view the world and those around you.",
    "Instead, use fear as a motivator.",
    "Is there a magic potion that will allow us to one day wake up positive and ready to be the most amazing person we can be?",
    "It equips us with the tools we need to make it through another day and brings us a step closer to happiness.",
    "It even seems easier to fall into a routine of using things to alter your reality.",
    "It gives us the opportunity to create and maintain a strong, healthy connection that can further allow us to be thankful for what we do have.",
    "It had been a few weeks since I last visited there, and besides, I figured that having people around me while working would be nice for a change.",
    "It has been shown that we use more facial muscles to frown than to smile, and our stress levels increase by worrying.",
    "It has been staring us in the face from day one, but we’ve just been too preoccupied with things that don’t matter.",
    "It haunts us from such a young age that the older we get is the more accustomed to it we are.",
    "It helps us to realize that not everything has to be perfect.",
    "It ignites within us a fire that allows us to be alive.",
    "It is about using 20 seconds of courage and looking in the mirror while asking yourself, “Am I the best person I can be to those around me?",
    "It is in these times of adversity that you stay true to being genuine.",
    "It is often said that the journey of life is often walked in one of two directions: the direction which everyone takes, or the direction you take by creating your own path.",
    "It is one that we all too often take for granted.",
    "It is patiently waiting for you to listen to its call to stand up as someone different, not caring what others may think.",
    "It is the seemingly “always-on” emotion that saps us of vital energy and resources.",
    "It is up to each and every one of us to decide what happens next.",
    "It is vital to seize every opportunity.",
    "It is within these paths that we are often walking blindly into the destruction of ourselves.",
    "It isn’t over.",
    "It isn’t to be lavished upon quick pleasures and vices.",
    "It makes no sense walking around with a frown or worrying about a problem.",
    "It may be a hard pill to swallow, but it must be done.",
    "It may be difficult, but declare that this is it, that you’ve had enough of life knocking you down.",
    "It may be difficult, but sort your items according to what you need, what you want, and what you absolutely do not need.",
    "It may feel as if you grew up too fast and somewhere along the road, your fun may have gotten lost.",
    "It must flow from within your inner spring.",
    "It nudges our souls with a hesitancy to get up and move forward, shaking our very being to the confines of another hopeful daydream.",
    "It seems we’ve gotten comfortable with things being average and mediocre.",
    "It takes a ton of courage to really stand up in a world where everything seems to just go from organized to chaotic within seconds.",
    "It took me 25 years to learn that while life can be bitter and harsh, good things can and will happen.",
    "It wants you to be confident in who you are as an individual since you are created for a special purpose.",
    "It was a tragic situation, especially for those of my friends who interacted with him on a regular basis.",
    "It was at a moment when I had the opportunity to be interviewed by one of the most innovative companies, and in the period of time in which things happened brought about a renewed vigor within me to launch my own business.",
    "It will allow you to appreciate and gain unexpected wisdom from unlikely places as it did for me.",
    "It won’t ever be easy, but like learning to ride a bike, it gets easier.",
    "It’s about what you do with what you have.",
    "It’s days like this, when the world seems to throw every ounce of difficulty your way, when it feels as if nothing is going your way, when all you want to do is hide in a dark place and cry your soul out.",
    "It’s easy to get lost in the shuffle of life, but when the blows of life come crashing down, look up.",
    "It’s easy to want control over everything in life, but what does that still small voice inside say?",
    "It’s funny, I tell this to my clients all the time, yet I often neglect to take my own medicine.",
    "It’s never too late to learn something new.",
    "I’m fearful that things are too good to be true, and I’m worried that as a person, I don’t deserve anything good.",
    "I’m not talking professionally or socially; I’m talking about your “inner” life.",
    "I’ve been a good person, why is nothing good happening to me?”",
    "I’ve spent a good portion of my life asking why.",
    "Joy helps us to remove the emotional and creative blocks that cage us in.",
    "Just remember, you aren’t in it alone.",
    "Know that knowledge is the key to a prosperous life.",
    "Learn more.",
    "Learn passionately.",
    "Let go and let God.",
    "Let that go.",
    "Let this process be one of renewal and rebirth.",
    "Let today, right now within this moment, be the moment you make the choice to give up fear.",
    "Let your emotional hue lose its cloudy nature and relax.",
    "Letting those who can help is the only way we will succeed.",
    "Let’s explore life.",
    "Let’s think about this for a second about rockets.",
    "Life has an interesting way of presenting moments in which you should give thanks for what you have.",
    "Life is way too short to not appreciate to its fullest, and I’m not referencing that ridiculous ”YOLO” phrase either.",
    "Life is what we make it.",
    "Life isn’t all bad unless you make it that way.",
    "Life was just getting interesting, and his goals right around the corner.",
    "Life will consistently give us ups and downs, and the struggle wins when we focus on nothing but the downs.",
    "Listen closely, because it has a question for you.",
    "Lonely and searching for a helping hand, begging for forgiveness in an unforgiving land, searching for something better, something to make the pain go away, only to come up empty at the end of the day.",
    "lost and struggling",
    "Lou Holtz once said, “Winners and losers aren’t born, they are the products of how they think.",
    "Love and compassion are necessities, not luxuries.",
    "Make the world awesome instead of dreadful.",
    "Many nights of solitude and inward reflection have brought out a few things I wish someone had told me throughout life:",
    "Many of the outcomes in our daily lives tend to rest solely on how we respond to them.",
    "Many of the problems we face in life are created within our own minds.",
    "Many of these people may have been forgotten because they had no one who cared about them.",
    "Many of us have experienced the overly chipper coworker that is always in a good mood.",
    "Master something.",
    "Maya Angelou illustrates this point so eloquently,",
    "Meet fear with excitement and vigor, for the giants we fear aren’t giants at all.",
    "Most importantly, there is a chance at influencing others around you in a more positive direction.",
    "Most of all, just like you I face obstacles.",
    "Most of all, trust God and never, ever give up.",
    "Most of us take life for granted.",
    "Most of what we assume is wrong.",
    "Most times, it isn’t due to bad luck or even other people.",
    "Must. Break. Chains.",
    "My unshakeable thought was, “What if now is my time?",
    "Neither can our purpose come from the phony advice of others who claim they have the “secret” to our purpose and happiness.",
    "Never give up.",
    "Never stop exploring the true capabilities of your skills.",
    "Never stop loving.",
    "Never stop pushing forward.",
    "New beginnings are fun and exciting.",
    "No matter how cool that new phone is or how up to date our technology is, at the end of the day we need each other.",
    "No matter how dark the day, things do and will get better.",
    "No matter the reason, deep within us is a burning desire to make the world around us a happier place.",
    "No matter what, wear a smile, but don’t be afraid to reach out and ask for help.",
    "No one but God knows you as well as you do.",
    "No one man has built a civilization on his own.",
    "None of us are.",
    "Not everything in life is about you or me.",
    "Not one person will know or carry the save-all solution, but if banded together, who knows what could happen?",
    "Not so pleasing I’d hope.",
    "Not the fireworks kind, but the kind that goes to space.",
    "Nothing worth having is ever easy to accomplish, but that doesn’t mean that you shouldn’t make the effort to take on the challenge.",
    "Now imagine from where ever you are on this line of extremes, your own feelings and mix of emotional cocktails.",
    "Now in no way do I suggest that you immediately join a church and that all your problems will be solved by this.",
    "Now is the time to stand up and take part in humanity.",
    "Now isn’t the time for dreams, but for hard work and a dedication to making this happen.",
    "Now I’m not talking about the “whining and screaming like a baby” cry, but a good, adult-like cry always helps.",
    "Now that I’ve spent over a couple decades on this earth, I can look back and say that despite my odds, life has been interestingly good to me.",
    "Now when I say need, I mean the items absolutely important to your day-to-day survival.",
    "Now, let’s go out and create some good.",
    "Of course, the downside to being a superhero is having a nemesis residing in us that is strategic and crippling.",
    "Often hidden in hours of procrastinating, we go back and forth with monologues of the many reasons why our goals may not be a good idea, or we listen to the advice of someone who may not understand.",
    "Often I pass what seems to be a growing number of people who have met the unfortunate side of life, the side where they are homeless and a place of their own is not within their reach.",
    "Often they are filled with feelings of shame, worthlessness, and a bruised pride.",
    "Often we face the overwhelming feeling that there is not enough time in the day.",
    "Often we forget the journey we had to take to get to where we are.",
    "On days like this, make a list of things that you’ve accomplished recently.",
    "On our journey together, we will explore avenues of giving in to the possibilities that surround you.",
    "On these days, you have to stare the difficulties down, power through the darkness and set your sights on the light at the end of the tunnel of struggle.",
    "Once a shining example, he’s now only a shell of his former self.",
    "Once accepted, you’ll begin to feel much better.",
    "Once you have gathered all the items you don’t need, give them away.",
    "Once you really start loving, you’ll feel renewed and invigorated.",
    "One day you may suddenly realize that you've gone from hanging out with friends and hating classes to paying bills and working towards goals others have set for you.",
    "One particular Monday was tough for me.",
    "One particular night was no different, except for some reason I couldn’t shake one thought from my mind.",
    "One popular quote states that work fits the time it is allotted.",
    "One-day things will be alright, but today we need to take a stand against the darkness, against the lack of care for our fellow man.",
    "Only by continuing on this path of working together can we make a better tomorrow possible.",
    "Onward.",
    "Or did I want to stand strong, be a winner, and calmly think about how the situation could be turned for good?",
    "Or will we get up and do the necessary work that needs to be done?",
    "Or would you pursue your passion with full vigor and vitality?",
    "Or would you seek to be of service to your fellow man?",
    "Our barista from the story earlier made the choice to take joy in her life.",
    "Our creativity blossoms when our surroundings are at peace, when the energy flowing around us is more than a quick emotional fix.",
    "Our environments have quite a bit to do with our everyday well being.",
    "Our greatest obstacle is that the more connected with fancy new technology we are, the more we lose a part of ourselves.",
    "Our journey through life should also take us upward.",
    "Our lives are very similar.",
    "Our mentality clouds who we are and can make us look like complete fools.",
    "Our minds happen to be the most perfectly flawed piece of technology, guided by a human interface that collects and analyzes billions of bits of information on a daily basis.",
    "Our poor mental habits cause an often distorted view of our surroundings.",
    "Our programming has a few bugs from one too many all-nighters and we lost sight of the goal before us.",
    "Our software needs an update.",
    "Outside of financial reasons, many relationships are destroyed by stupid misunderstandings.",
    "Overcoming limiting beliefs isn’t about discovering a magically new way to solve your problems.",
    "Overcoming that obstacle for me was tough, but I learned that the process was slow because I’m human, just like you.",
    "Pain only exists to make us stronger, to show us that sometimes things are bad, but despite these bad things, we can be so much more.",
    "Parenting, like anything worthwhile in life, is tough.",
    "Perhaps the issue isn’t our goals, but merely the means by which we go about achieving our goals.",
    "Procrastinate less.",
    "Procrastinating and pushing a dream or goal till the morrow is a waste of existence.",
    "Protect and love your children with everything you have.",
    "Reality can be horrible sometimes.",
    "Reality isn’t something to run from, but to instead embrace.",
    "Realizing that life is short helps us use the little time we have more wisely and for eternal good.",
    "Recently a person I knew back in my younger days passed away.",
    "Regardless of the obstacles standing in your way, hold your head up and trust in God.",
    "Regardless of who or what you believe in, there is a general understanding that in this world, you have two basic forces – good and evil.",
    "Releasing the fear allows the rain to wash away the pain of yesterday, bringing into view the blessings we so desperately search for.",
    "Remember what it was like when you actually cared.",
    "Remove the clutter in your surroundings.",
    "Restoring hope within",
    "Sadly no.",
    "Sadly not everyone has great experiences when the moment calls for it, but that means that we should look to change less-than-positive situations by paying kindness forward and turning the other cheek.",
    "Sadly we have been trapped with a one track mind.",
    "Save more.",
    "See, life isn’t about what you don’t have.",
    "Seize the moment, conquer the day, and aim always upward.",
    "Seize those moments of positivity; shy away from giving into a bad mood.",
    "Set the status quo then break it.",
    "She finished saying my order before I could, and after we made a few jokes, I asked myself, “How could I continue feeling down about Monday when the cheerful barista obviously wasn’t?”",
    "Simply dreaming about imaginary situations where you’ve succeeded on achieving your goal are great time wasters.",
    "Small steps make a difference.",
    "Smile like you mean it, while actually meaning it.",
    "So deal with it.",
    "So far, we’ve become aware that life wasn’t meant to be a rat race, but to be shared and enjoyed.",
    "So here I am.",
    "So how do we disconnect and find peace?",
    "So how do we move from constantly seeking more to being thankful for what we do have?",
    "So how does one find time to make time?",
    "So how does that revenge look now?",
    "So how will you be more positive starting today?",
    "So let’s create more good.",
    "So the question is why do we fear new beginnings?",
    "So what do we do when life seems to just throw you curve balls?",
    "So what is the secret to being able to embrace the struggle and win?",
    "Some may already be before us, however, if all we can perceive is the negative, we won’t be able to see the sunshine after the rain.",
    "Some may be simple enough for you to have that “come at me bro” type of mentality.",
    "Some of the greatest accomplishments have been achieved by the smallest things.",
    "Somehow, somewhere, we have the idea that we need to be told of how great we are.",
    "Someone was hurt before you, wronged before you, hungry before you, frightened before you, beaten before you, humiliated before you… yet, someone survived… [y]ou can do anything you choose to do.",
    "Someone will always do something to cause us an inconvenience, make us angry, or hurt us.",
    "Sometimes are thoughts will take us to better places and sometimes we'll have days where we come to grips with the battle that goes on within our minds, often without us realizing it.",
    "Sometimes it may seem as if there is only suffering, but on the other side of the struggle, remember that it is during our darkest times, He is the one carrying you through.",
    "Sometimes, life can just suck without us being able to do anything about it, and sometimes things may not be as bad as they seem.",
    "Sometimes, like in this case, it’s not a bad thing to tap into our inner child once again and explore our curious side.",
    "Somewhere along the way our wires got crossed.",
    "Soon, we find ourselves bouncing around from one bad moment to the next, completely oblivious to all the good that is happening.",
    "Stand proud.",
    "Stand tall, because with so many possibilities and outcomes that can bring joy to your life, why let those things pass you by?",
    "Stand tall.",
    "Standing on edge",
    "Standing on the edge, will I land on the target?",
    "Start feeling grateful for a change and see how much better you feel.",
    "Start saving this moment.",
    "Start today.",
    "Stay humble and pick yourself up.",
    "Staying motivated sometimes can be tough for me, especially on Mondays.",
    "Step outside your bubble.",
    "Stop choosing fear over achieving your goals.",
    "Stop looking for the bad in life.",
    "Stop trying to be everything to everyone or you’ll burn yourself out.",
    "Stop waiting on the right moment.",
    "Stop weighing your life down with the burden of that grudge.",
    "Stronger than before",
    "Sure bad will still exist, but within you, within the area around you, good things will balance out the scales.",
    "Sure it’s difficult, but we have to start somewhere or we’ll end up nowhere.",
    "Take a look around.",
    "Take a moment, whether it is once a day or once a week, to look back at how you’ve handled situations in the past, what path you tend to choose, and how you can use that experience in making better choices today.",
    "Take the time to number your days by asking, “What do I want to see happen in my life before I die?",
    "Tell yourself how great you are and then believe it! Then, get up and go do something with yourself.",
    "Thankfulness is a craft underused and often taken for granted.",
    "That bag of lemons isn’t a burden but is instead a blessing.",
    "That bag of lemons represent the bitterness of your life, but despite this, your life is still one filled with dreams of a better tomorrow and visions of a happier place.",
    "That doesn’t mean that you should just stand by and be defeated.",
    "That fact however isn’t of much importance.",
    "That God will carry you through?",
    "The abyss of fear and worry began to set in as I pondered over the fact that my chosen career can either be highly rewarding or terribly agonizing.",
    "The blame placed on society, technology or anywhere else except the source is now banned.",
    "The blood, sweat and bucket of tears are all here for a reason.",
    "The call given is to rise above average, stand with honor, and refuse to give in when we face hardship.",
    "The choice in the end is ours to focus on viewing things in a positive light.",
    "The count is going on, your body is weak from the pounding it has been given, yet somehow you will have the strength to pull yourself up and fight back.",
    "The end result will be a happier time on this earth.",
    "The fact is if you want something good to happen, do something to change your perception, branch out and do good things.",
    "The failure to seize a positive moment can lead to defeat.",
    "The familiar feeling of fear and anxiety tries to sneak up on us.",
    "The feeling of having our backs constantly pressed against a wall resonates to our very core.",
    "The journey of things being okay can now begin.",
    "The journey to being happier and healthier isn’t as simple as checking off a list of items; it is a holistic revamp of your life in its current state.",
    "The latter is normal, so don’t fight it, embrace it.",
    "The mission is to do good in all the world, to be of comfort and support for our fellow man.",
    "The moment you wake up each day should be filled with such joy and thankfulness that another day is here, there is another chance to do something good, and there is another chance to share this joy with others.",
    "The more our perception is trained, the more aware we become of the world around us.",
    "The most powerful factor is the commitment we make to make a difference by applying wisdom and understanding to our fellow man.",
    "The need for something tangible in our overly digital world drives us to a feeling of frustration.",
    "The next moment changed my life.",
    "The next time a situation has you down in the dumps, ask yourself what would happen in 5 years if you allow yourself to remain down?",
    "The only obstacle in the way of the reality of your daydreams is you.",
    "The only way we can continue to spread good throughout the world relies heavily on the generations to come.",
    "The person that seems to have luck on speed dial, but secretly, he or she is hurting and torn with worry and stress, and is often shuts away into the prison of his or her own mind.",
    "the personal brand",
    "The pressure grows to not mess up and to achieve something outstanding so that your parents will be proud.",
    "The question is what will you do in response?",
    "The rain that continued its attempt at dragging the mood down allowed for the opportunity to finally have a quick chat with one of the most insightful and down to earth individuals I’ve ever met.",
    "The space called life.",
    "The struggle loses when we consistently make the effort to find the good, and to embrace the good with the bad.",
    "The thought of fading into the distance, forgotten, haunts our deepest thoughts.",
    "The time for second guessing has passed.",
    "The time is now.",
    "The time is now.",
    "The time to be who God has called me to be is now.",
    "The time we have must be used wisely.",
    "The torment grows with each waking moment, followed by the fear of things that haven’t happened and probably never will.",
    "The trick isn’t to overcome fear, but to perform despite it.",
    "The twinkle of the remaining stars in the sky give me hope, strength and courage to keep pushing forward, and the darkness that remains somehow calms my soul.",
    "The very bonds that hold us back from being happy are broken and our spirits are renewed.",
    "The very thing you seek isn’t in a new car or fancy clothes, but instead resides deep within your soul.",
    "Their emotions are going up and down just as crazily and frequently as your emotions are.",
    "Their journey goes upward, pushing against the forces of gravity, and traveling to a destination only few have ever seen.",
    "Then we grew up and life became complicated.",
    "Then work hard to get there.",
    "Then, as each day progresses, you’ll start to notice a new pattern taking effect.",
    "There are days when life feels as if it may be utterly pointless to do anything.",
    "There are days when things feel too much to bear, and you wonder just what is keeping you going.",
    "There are those moments when adulthood and a longing for simplicity and fun will collide.",
    "There are times when giving up seems so easy, yet I am reminded that God has carried me all this way and that giving up would be foolish.",
    "There is a constant back and forth between surviving and doing the right thing.",
    "There is a new perspective to be gained, a new chance to create something special, even in the toughest of circumstances.",
    "There is no middle of the fence.",
    "Therefore, starting now, I need you to establish trust with your brain.",
    "There’s plenty to go around.",
    "These are paths that lead to the draining of our very being.",
    "These are the words of a boy, whose own thoughts have him trapped in the prison of his soul as if he’s someone’s toy.",
    "These thoughts are all burning through my soul.",
    "They allow us to connect with others, but most of all, they give us the strength to carry on.",
    "They allow us to find our passion for the things that matter.",
    "They allow us to find the courage and energy to take on the obstacles that barrage us daily.",
    "They aren’t aliens, no matter how strange they can be at times.",
    "They believe that being a part of a church community gives an experience of being revitalized after a week of being dragged through the mud.",
    "They challenge us to explore life from a different perspective.",
    "They don’t prepare you for life.",
    "They don’t tell you about the sleepless nights and the moments when all you can do is curl up in a ball and cry.",
    "They forget to mention how life is tough, or that going against the grain can oftentimes be lonely.",
    "They have a huge responsibility to carry cargo safely to a destination hundreds of thousands of miles away.",
    "They just seem larger from the shadows cast behind them that were created by the awesome light shining on us.",
    "They rely on you to know life will somehow be okay, that no matter how crazy life can be at times, there is more to it than all the things they’ve learned to dislike.",
    "They’re there to remind us that giving up would be a waste of time.",
    "Things began earlier than usual for me one fine Tuesday morning.",
    "Think of it as nature’s reset button.",
    "This boy could be me or you, or someone we know or may have passed by on the street.",
    "This doesn’t mean you’re admitting defeat or showing weakness; it just means that you’re human.",
    "This in itself is the biggest lie to all mankind.",
    "This is especially true if you haven’t started saving anything yet.",
    "This is it.",
    "This is my story, but it is a story that is too familiar with all of us.",
    "This is the area in which your personal brand can shine.",
    "This is the moment in life where it’s absolutely crucial that you get back up.",
    "This is the result of choosing to win in what seems like an impossible situation.",
    "This is the thought that moves along with our heartbeats.",
    "This is what happens when something outside of your comfort zone occurs.",
    "This is your time.",
    "This isn’t just any story, this is your story.",
    "This mindset has caused us to feel as if life is a joke.",
    "This moment has been coming for a long time and I realized that I didn’t prepare enough.",
    "This moment shouldn’t be about giving in and feeling down, but instead should be a moment where stress is released and by tapping into the inner spring of strength.",
    "This time we're prepared, this time we're stronger.",
    "This time, we're relying solely upon God.",
    "This way of thinking has led us to believe that it is bad to be vulnerable, that we should always appear strong.",
    "Those people around us are experiencing a multitude of things as well.",
    "Thoughts that leave you doubtful, hesitant, and feeling alone and scared.",
    "Throughout our journey, we’ll ask ourselves just what it is we truly want, what we’d like our legacies to be, and most importantly, how can we be genuinely happy.",
    "Throughout the maze of life we've somehow ended up stretched too thin.",
    "Time quickly passes on, the rules set to hold the poor and broken down.",
    "Time spent worrying and complaining is like robbing your personal bank of happiness.",
    "To be effective, the source of sharing good can’t be from an outside source.",
    "To be triumphant in the face of adversity is one important piece in achieving happiness.",
    "To break the barrier of fear, we need to start small.",
    "To continuously punish ourselves because someone else caused a bad day is insanity at its best.",
    "To feel fear is to be human, but we should never let it limit us from being the best person we can be.",
    "To forget how one gets somewhere is to forget one’s self.",
    "To give in to our fears would be giving in to defeat and frankly, if you’re anything like me, failure just isn’t an option.",
    "To hate is to die.",
    "To love is to live.",
    "To rise above average means to hold ourselves up to a higher standard, where the focus is outward instead of constantly inward.",
    "To some, including myself, church may bring about the solution for this.",
    "To tap into these feelings, we must first mend the connections within ourselves.",
    "To think we can accomplish this by ourselves is also insanity.",
    "Today we need to be the light, ever burning bright.",
    "Together, a collective group of people came together to make it all possible.",
    "Together, we must learn to love each other and our Maker because He loves us.",
    "Tomorrow isn’t promised to any of us.",
    "Tortured by a dark past, held captive by his thoughts, struggling to keep his held high, the pain only seems to grow.",
    "Track the small wins, as this will help to motivate you towards bigger accomplishments.",
    "Trust God.",
    "Truth is, adulthood is hard, and it doesn't matter what age you are.",
    "Truth is, I do deserve good things.",
    "Truth is, I’m just like anyone else.",
    "Truth is, you can’t do everything alone and even though we will never understand all of our emotions, crying helps to release our stress.",
    "Truth is, “someday” is not a day on the calendar.",
    "Two (or more) heads are better than one, so think on how you can band together with someone around you.",
    "Uncertainty may be everywhere, causing us to be hesitant in trusting others, sometimes for good reason.",
    "Unfortunately, there are times when this realization gets lost because we tend to be so self-absorbed, we can’t even see our own true selves and we therefore miss vital opportunities to grow as individuals and a society.",
    "Use it to live better and to challenge yourself to grow as an individual.",
    "Viewing fear as an obstacle will only make it grow bigger.",
    "Want to learn a new language?",
    "We all crave peace and happiness, yet somehow things around us are shrouded in fear and uncertainty.",
    "We all fear something.",
    "We all fight, but the question is, what are you fighting for?",
    "We all have fears and thoughts that keep us back from achieving our goals.",
    "We all need oxygen, we all need food, and all bleed red.",
    "We are all filled with unique talents that in their own rights are creative and waiting to burst at the seams.",
    "We are all good at something, for there is no such thing as a human being that is a waste of space.",
    "We are all ordinary people with the ability to do extraordinary things.",
    "We are all special and our purpose in life can’t be delivered in a shiny magazine outlining the items we must buy to stay trendy.",
    "We are called to hold each other up, standing shoulder to shoulder and moving forward.",
    "We are the editors and artists of our lives.",
    "We aren’t bound by any rule to win, for if in the end after all the fame and fortune, we are alone, then what is it all worth at the end of the day?",
    "We can be individuals set apart, tasked with the objective of helping those around us who may not be as strong to walk the path of fear alone.",
    "We can no longer hide from who we are.",
    "We can take that bag and turn life into a refreshing glass of lemonade.",
    "We constantly make empty promises to ourselves and others with the intention of fulfilling them, but in the moment of our desperation when we realize we can’t do so, we restlessly send up a prayer hoping that it’ll be heard and our wishes granted.",
    "We desperately desire that place where everything feels safe, and where one can heal from the tremendous burdens carried days before.",
    "We don’t like talking about death because it makes us uncomfortable, but this harsh reality can’t be outrun.",
    "We easily take personal paths that are often destructive, pushing away those who truly care in pursuit of a big break or better financial standing.",
    "We fail to realize that we’ve been through these things before and most importantly survived.",
    "We forgot how to be human.",
    "We forgot how to explore.",
    "We get so caught up in the way people perceive us and look so deeply into things that we take things so personally.",
    "We go about each day thinking that our accomplishments are our own, only saying a prayer when things go wrong.",
    "We have one small shot at being something worthwhile, and this is the seed that has been planted to keep us going.",
    "We have the hope of another day and the calming thought that today we did all that we could, the best way we could.",
    "We just happen to live in a world and time where preconceived notions of others often lead to horrible misunderstandings.",
    "We live in a world where parenting seems to be more of a burden and less of a blessing.",
    "We look around, crying out for help, but no one can hear us.",
    "We look inward, trying to find the one thing that fills that aching space inside.",
    "We must dislike it with such a passion that we put our all, our everything into doing some good.",
    "We must do what makes us uncomfortable.",
    "We must hold each other, especially when the other stumbles.",
    "We must raise our voices and shout for joy for all that is around us.",
    "We need each other.",
    "We need each other.",
    "We need to push forward and accomplish a better tomorrow, learning to love ourselves as an individual and not a brand or an example of how society says we should live.",
    "We never give up.",
    "We reach out, but no one is there.",
    "We should accept a calling to something more than just average and refuse to accept mediocre by striving to be exceptional.",
    "We should all go the extra mile in helping someone else meet their goals.",
    "We should be different.",
    "We should love our fellow man because we are no different.",
    "We should realize that no matter how many times we may fall, what counts the most is that we get up and brush ourselves off.",
    "We sit and complain about trivial things, like how our internet is down, or how our favorite drink is sold out.",
    "We spend so much time judging others that we fail to see the steaming pile of crap that we stand in.",
    "We think that only with wealth can we be truly happy.",
    "We try daily to avoid feeling the pain of rejection, disappointment, failure, and hopelessness.",
    "We use facades of being a lofty person or someone who has it all together, while on the inside we are falling apart like an old building.",
    "We, usually, allow the embodiment of failure to soak us to our very core, due to our human nature and our minds lacking the ability to see a much wider view.",
    "Well, it could be nothing more than they choose to be that way.",
    "We’re all facing similar struggles.",
    "We’ve also been bombarded with ideas about ourselves that originated from outside of who we are.",
    "We’ve also been magically suckered into thinking that we need to be chosen, or born special to accomplish something great.",
    "We’ve been conditioned to live our lives fearing our own selves.",
    "We’ve come to an age where hoarding and cluttering our lives can be easily accomplished with a click or even a tap of the finger.",
    "What choices will you make today?",
    "What choices will you make?",
    "What counts is here and now, the moment we’re alive and breathing.",
    "What does it mean?",
    "What happened next helped me to see the special glimmer that Mondays offered and set the pace for an amazing week.",
    "What if all our basic needs were taken care of, what would we do with our lives then?",
    "What if I can finally stand proud and be able to share my story of how God has led me throughout my life?”",
    "What if it didn’t matter if everything was perfect, but what did matter was putting dreams into actions?",
    "What is important is what we do with the time we have alive.",
    "What items, tangible and intangible, are holding you back?",
    "What I’m talking about is having a deep reflection of the life that you’re given and making the most of it.",
    "What makes you push beyond the pain, anger and confusion that seems to surround and suffocate your very existence?",
    "What more can I do besides give the occasional dollar?",
    "What situations are consistently weighing in on your emotions, causing you to miss out on the things now that are important?",
    "What small step could I take toward that purpose today?”",
    "What will you do today to master the fear that drives us apart?",
    "What will you do with them?",
    "What will you stand up for today?",
    "What would you do if you weren’t afraid?",
    "What would you do if you weren’t afraid?",
    "Whatever you do, NEVER GIVE UP.",
    "What’s their secret?",
    "When all the best-laid plans just seem to be hopeful wishes that feel inadequate?",
    "When did life get so hard?",
    "When good things happen, I get scared.",
    "When it feels as if nothing is going right, we are sometimes faced with dark thoughts that things just seem useless to live for.",
    "When it’s all over, what do you think you will be able to say?",
    "When we fail, it isn’t the end; it is a new beginning, a slate wiped clean and a new canvas to start with.",
    "When we look up to the Author of our very existence, we realize that each and every one of us is someone special someone with unique skills and abilities.",
    "When you feel as if you just can’t hold on any longer?",
    "When you start sharing with others the good you want to bring to this world and share with them your passion for doing so, you’ll begin to find new ways in which you can act upon this burning desire.",
    "Where are you overlooking joy in your life?",
    "Where does your passion lie and how can you use it to make a positive difference?",
    "Whether it’s $100 more or $1 more, always strive to save more than what you were saving before.",
    "Whether we realize it or not, to want to do good is to hate evil.",
    "Whether we seek to spend more time with loved ones, catching up on a good book that has been collecting dust on our shelf, or have the simple need for capturing a little more time to ourselves, we crave for that moment where time slows down and embraces us in its warmth.",
    "Whether you want to acknowledge it or not, we’re all human.",
    "Whether your aim is to be a lawyer, doctor or artist, aim high and never give up.",
    "While the above points are all important, this, to me, is the biggest thing I’ve learned and is also the most important.",
    "Who is he, and how did things end up this way?",
    "Whoever said that life gets easier was surely optimistic beyond belief, or was perhaps a realist who understood the importance of creating positive moments to live in.",
    "Why can’t I just help everyone in the world?",
    "Why do good people suffer?",
    "Why do we give up when we’re so close to achieving the goal we set out to?",
    "Why is life so weird?",
    "Why then would you want to put your body through all this?",
    "Will today be any different?",
    "Will today be the day I win the battle in the war that torments my soul?",
    "Will we sit idly by wishing on stars?",
    "Will you get mad and hold on to a grudge, or will you let it go?",
    "Will you?",
    "With all new beginnings - a marriage, baby, or starting a company based on something you’re passionate about, there will be inevitable hardships, but this can be overshadowed by the momentum and the possibility of achieving your dreams.",
    "With an early childhood plagued with insurmountable emotional odds, feelings of comfort were but a distant dream for me.",
    "With depression knocking on the door, it feels as if there needs to be more, even despite the success surrounding you.",
    "With each unique viewpoint coming together, imagine the possibilities of waking up to a day where people don’t just tolerate someone because a law says so, but instead loves those around them out of true desire to do so.",
    "With everything taken away, all possessions removed from the equation, your children are all you have.",
    "With Him, you’ll be stronger than ever.",
    "With love and compassion in our lives, we begin to learn about ourselves and we become emotionally smarter.",
    "With so much noise around us, our inner thoughts tend to get lost in the shuffle, and we often forget the importance of listening to the still small voice within us.",
    "With the ability to carry out our daily lives faster and cheaper, the act of constantly consuming and never giving back has caused us to lose our humanity and generosity.",
    "With the demands of raising a child and a lack of the village to provide support, we have been reduced to a “child manager” instead of a parent whom the child can come to.",
    "With the moment at hand and success so close it could be tasted, I now had the urge me to conquer the day.",
    "With this great power, we can choose whether the circumstances of life we face will result in positive or negative outcomes.",
    "With this in mind, however, our personal brands shouldn’t just be reflections of times long ago, but should be shared with others as a living example of believing and working towards social change.",
    "Within the most unlikely of circumstances, you will realize that the life you lead isn’t one that is always best.",
    "Within them are possibilities far beyond anything we can imagine with our limited understanding of life.",
    "Without them, humanity cannot survive.- Dalai Lama",
    "Would you attempt to gain more?",
    "Would you feel a longing to slave over reports or deadlines?",
    "Write down what you’re thankful and one thing you will do to have the outcome of your day be positive despite what may happen.",
    "Years ago when I set out to build a branding agency with a purpose, I didn’t quite realize just where the path would lead.",
    "Yes, I’m a guy and yes, I believe in crying.",
    "Yet others will knock you down farther than you’ve ever been.",
    "Yet somehow, each day we end up with less time than the day before, trapped within the mad rush we call our everyday lives.",
    "Yet things have gotten so intense, the only way to survive is to find extra strength and keep working.",
    "Yet, often it is this powerful tool that becomes our worst enemy.",
    "You and I can do the same.",
    "You are so fearful of what tomorrow may bring.",
    "You are still alive, and that is a lot to be thankful for.",
    "You beg for change; for something to go your way.",
    "You can make a difference because simply getting by is simply not good enough.",
    "You deserve good things too.",
    "You don’t have to accomplish something monumental.",
    "You don’t need to be told you’re awesome.",
    "You look in you [for Him].",
    "You should feel a sense of calm, relief and maybe a little sense of panic.",
    "You will release so much stress, and who knows, you might even come up with a million dollar idea.",
    "You will then find a renewed sense of ability to keep pushing on.",
    "Your life is now, so find your voice, your passion, be brave and fearless and take a chance.",
    "Your outlook not only allows you to live longer by being positive, it also allows you to be more successful in life.",
    "Zombified."
]

module.exports = (robot) ->
  robot.hear /(david)(.*)/i, (msg) ->
    msg.send msg.random remarks
